# Generated by Django 4.1.5 on 2023-01-16 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bids_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionlisting',
            options={'ordering': [models.OrderBy(models.F('id'), descending=True)]},
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='startBid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userListing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userBids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageURL',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.auctionlisting')),
            ],
        ),
    ]
