# Generated by Django 4.1.5 on 2023-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
