# Generated by Django 4.1.5 on 2023-01-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_categories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
