# Generated by Django 4.1.5 on 2023-01-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_categories_id_alter_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
