# Generated by Django 4.1.5 on 2023-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_comments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
