# Generated by Django 4.1.5 on 2023-01-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_remove_auctionlisting_watchlist_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist',
        ),
    ]
